### ISSUE TITLE
As an admin-friendly alternative for query for assignees, have it take in a collection instead?

### ISSUE THREAD

**Issue by ssk42** [jamessimone/salesforce-round-robin#11]
Could that be a potential PR?

**Comment by jamessimone** [comment]
@ssk42 sure! Love that idea.

**Comment by allisonletts** [comment]
I'd love a collection for assignees!

**Comment by jamessimone** [comment]
@allisonletts thanks for chiming in! That really helps to know. @ssk42 were you interested in making a contribution or should I take this one?
