### ISSUE TITLE
Issue when you are a member of the Group your are using for the Round Robin assignment

### ISSUE THREAD

**Issue by jmsctm** [jamessimone/salesforce-round-robin#13]
Not sure if it it stops working, or if it always selects your userid from the group - but either way, you are always assigned as the owner of he new record.

When you remove yourself from the group - it then starts selecting members from the group as required

**Comment by jamessimone** [comment]
Fascinating. I'll have to have a look. There's no reason any user should trump another one!

**Comment by jmsctm** [comment]
No worries @jamessimone - as always, thank you for your commitment to the community and the eco-system overall!

**Comment by jamessimone** [comment]
Of course - and a huge thanks to you, as well, for taking the time to file an issue. I know it's not ideal when software doesn't work the way we want it to, but I absolutely appreciate you for giving me the chance to make the Round Robin Assigner better for everyone.
