### ISSUE TITLE
Custom Setting Name too long

### ISSUE THREAD

**Issue by allisonletts** [jamessimone/salesforce-round-robin#16]
I'm trying to use this repo for round-robin assignment of records to a parent to avoid data skew. I'm coming across the following error: `FIELD_INTEGRITY_EXCEPTION, Custom Setting Name too long: npsp__Allocation__c.npsp__General_Accounting_Unit__c: Name: [Name]`

It looks like the limit is 38 characters for custom settings. Any chance of handling that error directly?

**Comment by jamessimone** [comment]
@allisonletts great callout - I can definitely handle this. I always forget about the lower name for custom settings.

**Comment by allisonletts** [comment]
fwiw, I ended up editing the code to just use `getLocalName()` and remove the ownerFieldApiName when it's looking at a collection, like this: 


```
private RoundRobinAssigner.Details getAssignmentDetails(FlowInput input) {
    RoundRobinAssigner.Details details = new RoundRobinAssigner.Details();
    if (input.recordsToRoundRobin.isEmpty() == false) {
      details.assignmentType = input.recordsToRoundRobin[0].getSObjectType().getDescribe().getLocalName();
    } else {
      details.assignmentType = input.ownerFieldApiName;
    }
    details.ownerField = input.ownerFieldApiName;
    return details;
  }
```

**Comment by jamessimone** [comment]
@allisonletts I've added an additional property, `Name For Custom Setting Record`, to the flow action to facilitate what you were previously doing in code (eg, if you want to use the output of `npsp__Allocation__c.SObjectType.getDescribe().getLocalName()`, you'd assign it using that property). Thanks again for pointing out this issue, and I hope that helps!
