### ISSUE TITLE
Maximum Stack Depth Reached

### ISSUE THREAD

**Issue by gpuviani** [jamessimone/salesforce-round-robin#8]
Scenario: 
- am implementing this for a client in an existing implementation and am forced to run this as an after save.
- have this running in a scheduled flow, batches of 10 leads, 1 mins after lead insert

When inserting 200 leads through data loader, regardless of batch size (except 1) and time delay (up to 2 mins) the first 50 leads are successfully inserted, after which I receive a message: Maximum Stack Depth Reached: 1001

Thanks for your help!

**Comment by jamessimone** [comment]
Do you have the full stack trace for the error message? Do you have any recursion in your flows or triggers?

**Comment by gpuviani** [comment]
Sadly I only have the error message provided in the flow:

Error element Assign_Via_Round_Robin (FlowActionCall).
An Apex error occurred: System.LimitException: Maximum stack depth reached: 1001 --- An Apex error occurred: System.LimitException: Maximum stack depth reached: 1001 --- An Apex error occurred: System.LimitException: Maximum stack depth reached: 1001 --- An Apex error occurred: System.LimitException: Maximum stack depth reached: 1001 --- An Apex error occurred: System.LimitException: Maximum stack depth reached: 1001

**Comment by jamessimone** [comment]
OK, I will take a look and get back to you!

**Comment by gpuviani** [comment]
Amazing thank you!!

**Comment by jamessimone** [comment]
@gpuviani I haven't been able to reproduce this issue locally - however, I am creating a new package version #9 which may help with some of these issues. I think a screenshot of your Flow input setup, and a log if you are able to attach that (the log that fails) would be helpful.

My gut is saying that you have a recursive process which is updating the leads you're inserting more times than is necessary. With the package version I am about to release, I've included some updates which may help with that, but if that doesn't address the issue we'll have to troubleshoot more with what I've requested above.

**Comment by gpuviani** [comment]
Hi James, thanks for your support on this. Sadly I am now also getting an error : Unable to lock row on the round robin records themselves. Would setting up some time help? Thanks again.

**Comment by jamessimone** [comment]
@gpuviani I'm afraid I don't have the bandwidth at the moment to do something like a call. The next two months will be quite busy for me. I am committed to helping asynchronously on this issue.

This morning, I was testing an update to seventy five opportunities where the Flow Action to round robin was being called without issue, but I'll try to take another look when I have the chance to see if I can reproduce the issues you've been having.

**Comment by jamessimone** [comment]
Closing, haven't been able to repro
